apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: gcs-workflow

on:
  push:
    branches:
      - '**'

jobs:
  custom:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
