apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'

jobs:
  custom-action:
    steps:
    - name: Checkout
      uses: cloudbees-io/checkout@v1